### ISSUE TITLE
Limitation in Name Export for Strokes Even with "Export Names" Enabled

### ISSUE THREAD

**Issue by behnamsattar** [JSimonDev/rive_color_modifier#5]
Hello,

Following up on the issue I previously reported ([issue link](https://github.com/JSimonDev/rive_color_modifier/issues/3)), I have encountered another limitation with the name exporting in Rive files. Despite enabling the "Export names" setting as suggested in the first issue, I found that the names for certain elements, specifically strokes intended for color changes, are still not being exported. This seems to point to a shortcoming in the current approach of handling names in the export process.

Upon further investigation, it appears that exporting the file for backup (available only to Rive Pro users), as opposed to exporting the runtime version (which strips out additional information to keep the file size small), might be the only solution. The runtime version seems to omit certain details crucial for the functionality provided by RiveColorModifier.

Suggestion:
Given this limitation, it might be beneficial for other users to know about this potential need for a Pro account to fully utilize all features of Rive with third-party packages that modify properties such as color at runtime.

Could we perhaps consider documenting this limitation or exploring ways to ensure that critical names and properties are retained in the runtime export for non-Pro users?

Thank you once again for your attention to these matters. Insights or solutions to this issue would greatly enhance the usability of your package in projects relying on detailed Rive animations.

**Comment by JSimonDev** [comment]
I’ve released version 2.1.1 of the package, where I mention in the documentation the issue with the new export method in Rive. However, I’m still looking for a way to assign names to Fills and Strokes in the runtime version of the .riv file so that non-Pro users can continue using the package comfortably. In the meantime, with the regular expression ".*," you can modify all unnamed Fills and Strokes (""). I’m going to close this issue for now; thank you for your contribution to improving the package. Your observations have been very helpful for this new version.
